export const VIEW_PROPS: any = {
  filters: {
    state: null,
    labels: null,
    priority: null,
    assignees: null,
    created_by: null,
    start_date: null,
    subscriber: null,
    state_group: null,
    target_date: null,
  },
  display_filters: {
    type: null,
    layout: 'list',
    group_by: null,
    order_by: '-created_at',
    sub_issue: true,
    show_empty_groups: true,
    calendar_date_range: '',
  },
  display_properties: {
    key: true,
    link: true,
    state: true,
    labels: true,
    assignee: true,
    due_date: true,
    estimate: true,
    priority: true,
    created_on: true,
    start_date: true,
    updated_on: true,
    sub_issue_count: true,
    attachment_count: true,
  },
};
export const DEFAULT_PROPS: any = {
  filters: {
    state: null,
    labels: null,
    priority: null,
    assignees: null,
    created_by: null,
    start_date: null,
    subscriber: null,
    state_group: null,
    target_date: null,
  },
  display_filters: {
    type: null,
    layout: 'list',
    group_by: null,
    order_by: '-created_at',
    sub_issue: true,
    show_empty_groups: true,
    calendar_date_range: '',
  },
  display_properties: {
    key: true,
    link: true,
    state: true,
    labels: true,
    assignee: true,
    due_date: true,
    estimate: true,
    priority: true,
    created_on: true,
    start_date: true,
    updated_on: true,
    sub_issue_count: true,
    attachment_count: true,
  },
};
export const ISSUE_PROPS: any = {
  created: true,
  assigned: true,
  all_issues: true,
  subscribed: true,
};
export const NOTIFICATION_DATA: any = {
  issue: {
    id: '127789a2-cd8e-4522-b979-2a37e227cdbd',
    name: 'First Work Item',
    identifier: 'NEWPR',
    state_name: 'In Progress',
    sequence_id: 1,
    state_group: 'started',
  },
  issue_activity: {
    id: '33e8a457-1fcc-4951-adce-382f6975303a',
    verb: 'updated',
    actor: 'None',
    field: 'state',
    new_value: 'In Progress',
    old_value: 'Backlog',
    issue_comment: '',
    new_identifier: '082f560e-6bb6-47e3-b218-5598f28aca6a',
    old_identifier: '84edca4d-d576-41f6-816b-dece47a5e067',
  },
};
export const ONBOARDING_STEPS: any = {
  workspace_join: false,
  profile_complete: false,
  workspace_create: false,
  workspace_invite: false,
};
export const MOBILE_ONBOARDING_STEPS: any = {
  workspace_join: false,
  profile_complete: false,
  workspace_create: false,
};
